### ISSUE TITLE
Remove the updater messages

### ISSUE THREAD

**Issue by kerostampcrab** [OMGitzFROST/PlayerLogs#6]
I don't understand its point and neither does any other 'bigger' plugin have it. It's just unnecessary spam to console, of course I know I disabled the updater!

**Comment by OMGitzFROST** [comment]
Just Updated to v1.2! It includes this adjustment as well, check it out when you can:

https://github.com/OMGitzFROST/PlayerLogs/releases/download/v1.2/PlayerLogs-1.2.jar
